# Generated by Django 5.2.5 on 2025-08-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_motorcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcomment',
            name='racer',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
