# Generated by Django 5.2.5 on 2025-08-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_motorcomment_racer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('role', models.CharField(choices=[('MC', 'MC'), ('解説者1', '解説者1'), ('解説者2', '解説者2'), ('ゲスト', 'ゲスト'), ('メモ', 'メモ')], default='MC', max_length=20)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RaceDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('type', models.CharField(choices=[('none', '非開催'), ('toshi', '都市開催'), ('minou', '箕面開催')], default='none', max_length=10)),
                ('title', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
