# Generated by Django 5.2.5 on 2025-08-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_event_raceday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceday',
            name='date',
            field=models.DateField(),
        ),
    ]
