# Generated by Django 5.2.5 on 2025-09-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_raceday_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('organizer', models.CharField(choices=[('都市', '都市'), ('箕面', '箕面')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('title', models.CharField(max_length=150)),
                ('days', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': '開催情報',
                'verbose_name_plural': '開催情報',
                'ordering': ['start_date', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('days__gte', 1)), name='days_gte_1'), models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='end_after_start')],
                'unique_together': {('organizer', 'start_date', 'title')},
            },
        ),
    ]
