# Generated by Django 5.2.5 on 2025-09-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcomment',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
