# Generated by Django 5.2.5 on 2026-03-10 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_motorcomment_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
