# Generated by Django 5.2.5 on 2026-07-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcomment',
            name='boat_no',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='motorcomment',
            name='parts_exchange',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='motorcomment',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
