# Generated by Django 5.2.5 on 2025-10-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RacerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toban', models.IntegerField(max_length=8)),
                ('name', models.CharField(max_length=20)),
                ('kana', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '参照用選手データ',
                'verbose_name_plural': '参照用選手データ(plural)',
            },
        ),
    ]
