# Generated by Django 5.2.5 on 2025-10-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racer_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racerdata',
            name='toban',
            field=models.IntegerField(),
        ),
    ]
